default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: project_development
  host: host.docker.internal
  username: diversepixel
  password: 9872

test:
  <<: *default
  database: project_test
  host: host.docker.internal
  username: diversepixel
  password: 9872

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
